[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
    sepolia = "https://eth-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    arbitrum_sepolia = "https://arb-sepolia.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    polygon_amoy = "https://polygon-amoy.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"
    polygon = "https://polygon-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[etherscan]
    arbitrum_sepolia = { key = "${ARBISCAN_API_KEY}" }
    sepolia = { key = "${ETHERSCAN_API_KEY}" }
    mainnet = { key = "${ETHERSCAN_API_KEY}" }
    polygon = { key = "${POLYGONSCAN_API_KEY}" }
    polygon_amoy = { key = "${POLYGONSCAN_API_KEY}" }
    
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
